### ISSUE TITLE
Ghostery o ublock?

### ISSUE THREAD

**Issue by ORARiccardo** [vecna/itatopex#3]
Ho visto che sulla landing page linki a ublock origin, però poi di là metti ghostery. E' meglio fare lo stesso oppure è una scelta precisa?

**Comment by vecna** [comment]
ho messo ublock perché é quello che più mi viene suggerito, poi ho messo ghostery perché da un miglior controllo e visualizzazione di quello che succede (ma ci sono dubbi su come monetizzi e quindi non lo suggerivo come prima scelta). dovrei prima o poi avere una scorecard degli adblocker ...

**Comment by ORARiccardo** [comment]
Sì, vero ne avevo sentito parlare anche io sui dubbi per la monetizzazione di ghostery. Ora capisco meglio la scelta.

Privacy Badger¹, invece, hai avuto modo di testarlo?

Una scorecard sarebbe veramente perfetta.

1 https://www.eff.org/privacybadger

**Comment by vecna** [comment]
privacybadger va aggiunto di certo, ha il limite che non funziona su mobile, ma lo metto, tnx

**Comment by ORARiccardo** [comment]
Vero, purtroppo quello è un grosso limite
